version: '3'
services:
  modelserver:
    image: opennmt/tensorflow-serving:2.0.0-gpu
    ports:
      - 8500:8500
      - 8501:8501
    volumes:
      - ./conf/models:/models
    command: --port=8500 --rest_api_port=8501 --model_config_file=/models/models.conf --rest_api_timeout_in_ms=300000
  nnserver:
    image: mideind/nnserver:latest
    ports:
      - 5005:5005
    environment:
      - MS_HOST=modelserver
      - MS_PORT=8501
      - NNSERVER_PARSING_VOCAB=parsing_tokens_191202.txt
    depends_on:
      - modelserver
